version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/build_native_library"
    schedule:
      interval: "daily"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/build_native_library/env_variables"
    schedule:
      interval: "daily"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/build_native_library/setup"
    schedule:
      interval: "daily"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/build_native_library/setup/jdk11"
    schedule:
      interval: "daily"

  # Maintain dependencies for maven
  - package-ecosystem: "maven"
    directory: "/java"
    schedule:
      interval: "daily"
